"""Fits the per-group linear scaling that puts our role-weighted overall on the same scale
as a reference rating (e.g. EA's overall), writing data/config/calibration/overall_scaling.yaml.

Only the scale is borrowed: which attributes matter for which role stays our own design. Each
group's scaling matches the reference's mean and spread (not a least-squares fit, which would
shrink the spread wherever our overall weighs things differently: the best players would no
longer reach the reference's top).
"""

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from footsim.defs.loader import GameDefinitions
from footsim.defs.positions import PositionGroup
from footsim.domain.attributes import ATTRIBUTES
from footsim.importers.records import SourcePlayer
from footsim.ratings.overall import RatingModel

MIN_PLAYERS = 20


@dataclass(frozen=True)
class GroupFit:
    group: PositionGroup
    players: int
    scale: float
    offset: float
    r2: float
    mae: float


def fit_overall_scaling(defs: GameDefinitions, players: list[SourcePlayer]) -> list[GroupFit]:
    """``players`` need completed attributes and a source overall."""
    rated = [p for p in players if p.source_overall is not None]
    matrix = np.array([[p.attrs[a] for a in ATTRIBUTES] for p in rated], dtype=np.float64)
    raw = RatingModel.build(defs).group_overalls(matrix)
    target = np.array([p.source_overall for p in rated], dtype=np.float64)
    primary = np.array([defs.positions[p.position].group for p in rated], dtype=object)

    fits = []
    for group in PositionGroup:
        mask = primary == group
        if int(mask.sum()) < MIN_PLAYERS:
            continue
        x, y = raw[group][mask], target[mask]
        scale = float(y.std() / x.std())
        offset = float(y.mean() - scale * x.mean())
        predicted = scale * x + offset
        ss_res = float(((y - predicted) ** 2).sum())
        ss_tot = float(((y - y.mean()) ** 2).sum())
        fits.append(
            GroupFit(
                group=group,
                players=int(mask.sum()),
                scale=float(scale),
                offset=float(offset),
                r2=1.0 - ss_res / ss_tot if ss_tot else 1.0,
                mae=float(np.abs(y - predicted).mean()),
            )
        )
    return fits


def write_scaling(path: Path, fits: list[GroupFit], reference: str) -> None:
    lines = [
        "# Generated by `footsim calibrate-overall`; do not edit by hand.",
        f"# Linear scaling of our role-weighted overall onto {reference}.",
        "# r2 / mae: how well the scaled overall reproduces the reference, per position group.",
        "groups:",
    ]
    for fit in fits:
        lines.append(
            f"  {fit.group.value}: {{scale: {fit.scale:.4f}, offset: {fit.offset:.3f}}}"
            f"  # n={fit.players} r2={fit.r2:.3f} mae={fit.mae:.2f}"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
